### ISSUE TITLE
Custom keys

### ISSUE THREAD

**Issue by MaxHasADHD** [insidegui/CloudKitCodable#5]
Is it possible to add support for custom keys? In CloudKit I have a property like "archived" but I'd want to define it as `let isArchived: Bool`

**Comment by insidegui** [comment]
Doesn't it work with the regular Codable mechanism of customizing keys?

```swift
struct MyThing: Codable {
    let isArchived: Bool

    enum CodingKeys: String, CodingKey {
        case isArchived = "archived"
    }
}
```
